### ISSUE TITLE
Upgrade ubuntu base

### ISSUE THREAD

**Issue by ConnorNelson** [angr/ci-settings#14]
https://github.com/angr/ci-settings/blob/514bc0b624dfb33828e4329414d6d0f154d2fa37/docker/Dockerfile#L1

The beaver is dead. Long live the fossa.

This base contains libc-2.27. While the rest of angr might be living in the past, archr is not. The testcases for archr are failing because of this ancient beaver. Upgrading should resolve angr/archr#70.

**Comment by twizmwazin** [comment]
Closing this for now, as I think it is preferable to keep 18.04 for CI since it better represents our intended minimum requirements, and the motivating issue has been resolved.
