### ISSUE TITLE
Make descriptive error messages show up in the github interface

### ISSUE THREAD

**Issue by rhelmot** [angr/ci-settings#21]
I can't find any documentation for this, but I _believe_ that we can change the "Bash exited with code 1" message to whatever we want by emitting a line that looks like `##[error]My error message goes here`.

**Comment by twizmwazin** [comment]
I actually started experimenting with this to try and surface lint failures to the github UI. See the `feat/log-lint` branch. [Here](https://github.com/angr/cle/runs/2936719962) is a commit where I was doing some testing on this.

**Comment by rhelmot** [comment]
I see... it seems that this is harder than just adding that tag :(

**Comment by twizmwazin** [comment]
We now use github actions and the output is now part of the github interface.
