### ISSUE TITLE
Move to PEP 517

### ISSUE THREAD

**Issue by FantasqueX** [angr/ci-settings#27]
I find that CI is using `python setup.py bdist_wheel` and all of projects of angr have been added pyproject.toml. So using `python -m build` the same as setuptools [document ](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use)is more prefered.

**Comment by twizmwazin** [comment]
We're now using a combination of cibuildwheel and `python -m build` for building wheel, both of which can/do use PEP 517.
