### ISSUE TITLE
Recreating a build locally fails due to error in script

### ISSUE THREAD

**Issue by dnivra** [angr/ci-settings#6]
The instructions in [README.md](https://github.com/angr/ci-settings/blob/master/README.md) for recreating a CI build locally do not work correctly:

```bash
$ docker run -it angr/ci:2 "https://dev.azure.com/angr/angr/_build/results?buildId=3494"
Traceback (most recent call last):
  File "/root/scripts/archive_url.py", line 8, in <module>
    api_url = re.search('https:[^"]*Builds/[0-9]*', requests.get(url).text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
http://: Invalid host name.
```

**Comment by rhelmot** [comment]
Amazing, azure pipelines changed their url schema. The script might need more in-depth fixing because it does some pretty janky html scraping...

If you want to do the build manually, start the container with bash as the startup program and download the archive from the azure artifacts.

**Comment by twizmwazin** [comment]
We've moved to github actions which requires authentication to even download the artifact, so unfortunately I don't see this script making a return.
